-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Lang.

module Lang.Abs where

import Prelude (String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Gen = Gen PExp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PExp
    = PLet Ident PExp PExp
    | PBind Ident PExp PExp
    | PIf PExp PExp PExp
    | PGuard PExp PExp
    | PLambda Ident PTyp PExp
    | PLambdaT Ident PExp
    | PPlus PExp PExp
    | PReturn PExp
    | PDistr PTyp
    | PProj PExp Ident
    | PAppT PExp PTyp
    | PProd [PLabExp]
    | PSum PTyp PLabExp
    | PCase PExp PTyp [PCaseExp]
    | PRec PExp Ident PExp PExp
    | PApp PExp PExp
    | PBoolT
    | PBoolF
    | PVar Ident
    | PZero
    | PSucc PExp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PLabExp = PLabExp Ident PExp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PCaseExp = PCaseExp Ident Ident PExp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data PTyp
    = PTBool
    | PTVar Ident
    | PTArr PTyp PTyp
    | PTDist PTyp
    | PTProd [TMember]
    | PTSum [TMember]
    | PTAll Ident PTyp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data TMember = TMember Ident PTyp | TMember1 Ident PTyp
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

