-- File generated by the BNF Converter (bnfc 2.9.6.3).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for Lang.

module Lang.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Lang.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Lang.Abs.Ident where
  prt _ (Lang.Abs.Ident i) = doc $ showString i
instance Print Lang.Abs.Gen where
  prt i = \case
    Lang.Abs.Gen pexp -> prPrec i 0 (concatD [prt 0 pexp])

instance Print Lang.Abs.PExp where
  prt i = \case
    Lang.Abs.PLet id_ pexp1 pexp2 -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 1 pexp1, doc (showString "in"), prt 0 pexp2])
    Lang.Abs.PBind id_ pexp1 pexp2 -> prPrec i 0 (concatD [prt 0 id_, doc (showString "~"), prt 3 pexp1, doc (showString "in"), prt 0 pexp2])
    Lang.Abs.PIf pexp1 pexp2 pexp3 -> prPrec i 1 (concatD [doc (showString "if"), prt 6 pexp1, doc (showString "then"), prt 1 pexp2, doc (showString "else"), prt 1 pexp3])
    Lang.Abs.PGuard pexp1 pexp2 -> prPrec i 0 (concatD [doc (showString "filter"), prt 6 pexp1, doc (showString "in"), prt 0 pexp2])
    Lang.Abs.PLambda id_ ptyp pexp -> prPrec i 2 (concatD [doc (showString "\\"), prt 0 id_, doc (showString "::"), prt 0 ptyp, doc (showString "->"), prt 1 pexp])
    Lang.Abs.PLambdaT id_ pexp -> prPrec i 2 (concatD [doc (showString "/\\"), prt 0 id_, doc (showString "=>"), prt 1 pexp])
    Lang.Abs.PPlus pexp1 pexp2 -> prPrec i 2 (concatD [prt 2 pexp1, doc (showString "+"), prt 3 pexp2])
    Lang.Abs.PReturn pexp -> prPrec i 3 (concatD [doc (showString "return"), prt 4 pexp])
    Lang.Abs.PDistr ptyp -> prPrec i 3 (concatD [doc (showString "distr"), prt 0 ptyp])
    Lang.Abs.PProj pexp id_ -> prPrec i 5 (concatD [prt 5 pexp, doc (showString "."), prt 0 id_])
    Lang.Abs.PAppT pexp ptyp -> prPrec i 5 (concatD [prt 6 pexp, doc (showString "["), prt 0 ptyp, doc (showString "]")])
    Lang.Abs.PProd plabexps -> prPrec i 6 (concatD [doc (showString "<"), prt 0 plabexps, doc (showString ">")])
    Lang.Abs.PSum ptyp plabexp -> prPrec i 6 (concatD [doc (showString "inj"), prt 0 ptyp, doc (showString "{"), prt 0 plabexp, doc (showString "}")])
    Lang.Abs.PCase pexp ptyp pcaseexps -> prPrec i 6 (concatD [doc (showString "case"), prt 0 pexp, doc (showString "of"), prt 0 ptyp, doc (showString "{"), prt 0 pcaseexps, doc (showString "}")])
    Lang.Abs.PRec pexp1 id_ pexp2 pexp3 -> prPrec i 6 (concatD [doc (showString "iter"), doc (showString "{"), prt 0 pexp1, doc (showString ";"), prt 0 id_, doc (showString ";"), prt 0 pexp2, doc (showString "}"), doc (showString "("), prt 7 pexp3, doc (showString ")")])
    Lang.Abs.PApp pexp1 pexp2 -> prPrec i 6 (concatD [prt 6 pexp1, prt 0 pexp2])
    Lang.Abs.PVar id_ -> prPrec i 6 (concatD [prt 0 id_])
    Lang.Abs.PBoolT -> prPrec i 7 (concatD [doc (showString "True")])
    Lang.Abs.PBoolF -> prPrec i 7 (concatD [doc (showString "False")])
    Lang.Abs.PZero -> prPrec i 7 (concatD [doc (showString "Z")])
    Lang.Abs.PSucc pexp -> prPrec i 7 (concatD [doc (showString "S"), doc (showString "("), prt 0 pexp, doc (showString ")")])

instance Print Lang.Abs.PLabExp where
  prt i = \case
    Lang.Abs.PLabExp id_ pexp -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 pexp])

instance Print [Lang.Abs.PLabExp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Lang.Abs.PCaseExp where
  prt i = \case
    Lang.Abs.PCaseExp id_1 id_2 pexp -> prPrec i 0 (concatD [prt 0 id_1, prt 0 id_2, doc (showString "->"), prt 0 pexp])

instance Print [Lang.Abs.PCaseExp] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print Lang.Abs.PTyp where
  prt i = \case
    Lang.Abs.PTBool -> prPrec i 0 (concatD [doc (showString "Bool")])
    Lang.Abs.PTNat -> prPrec i 0 (concatD [doc (showString "Nat")])
    Lang.Abs.PTVar id_ -> prPrec i 0 (concatD [prt 0 id_])
    Lang.Abs.PTArr ptyp1 ptyp2 -> prPrec i 0 (concatD [doc (showString "Arr"), prt 0 ptyp1, prt 0 ptyp2])
    Lang.Abs.PTDist ptyp -> prPrec i 0 (concatD [doc (showString "Dist"), prt 0 ptyp])
    Lang.Abs.PTProd tmembers -> prPrec i 0 (concatD [doc (showString "<"), prt 0 tmembers, doc (showString ">")])
    Lang.Abs.PTSum tmembers -> prPrec i 0 (concatD [doc (showString "{"), prt 1 tmembers, doc (showString "}")])
    Lang.Abs.PTAll id_ ptyp -> prPrec i 0 (concatD [doc (showString "forall"), prt 0 id_, doc (showString "."), prt 0 ptyp])

instance Print Lang.Abs.TMember where
  prt i = \case
    Lang.Abs.TMember id_ ptyp -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 ptyp])
    Lang.Abs.TMember1 id_ ptyp -> prPrec i 1 (concatD [prt 0 id_, doc (showString ":"), prt 0 ptyp])

instance Print [Lang.Abs.TMember] where
  prt 1 [x] = concatD [prt 1 x]
  prt 1 (x:xs) = concatD [prt 1 x, doc (showString "|"), prt 1 xs]
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]
