-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLang where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLang

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: AbsLang.Ident -> Result
transIdent x = case x of
  AbsLang.Ident string -> failure x

transGen :: AbsLang.Gen -> Result
transGen x = case x of
  AbsLang.Gen vdefs -> failure x

transVdef :: AbsLang.Vdef -> Result
transVdef x = case x of
  AbsLang.VdefQ ident ptyp pexp -> failure x

transPExp :: AbsLang.PExp -> Result
transPExp x = case x of
  AbsLang.PLet ident pexp1 pexp2 -> failure x
  AbsLang.PBind ident pexp1 pexp2 -> failure x
  AbsLang.PIf pexp1 pexp2 pexp3 -> failure x
  AbsLang.PGuard pexp1 pexp2 -> failure x
  AbsLang.PLambda ident pexp -> failure x
  AbsLang.PLambdaT ident pexp -> failure x
  AbsLang.PPlus pexp1 pexp2 -> failure x
  AbsLang.PReturn pexp -> failure x
  AbsLang.PDistr pexp -> failure x
  AbsLang.PProj pexp ident -> failure x
  AbsLang.PAppT pexp ptyp -> failure x
  AbsLang.PProd plabexps -> failure x
  AbsLang.PSum ptyp plabexp -> failure x
  AbsLang.PCase pexp ptyp pcaseexps -> failure x
  AbsLang.PVar ident -> failure x
  AbsLang.PBoolT -> failure x
  AbsLang.PBoolF -> failure x
  AbsLang.PApp pexp1 pexp2 -> failure x

transPLabExp :: AbsLang.PLabExp -> Result
transPLabExp x = case x of
  AbsLang.PLabExp ident pexp -> failure x

transPCaseExp :: AbsLang.PCaseExp -> Result
transPCaseExp x = case x of
  AbsLang.PCaseExp ident1 ident2 pexp -> failure x

transPTyp :: AbsLang.PTyp -> Result
transPTyp x = case x of
  AbsLang.PTBool -> failure x
  AbsLang.PTVar ident -> failure x
  AbsLang.PTArr ptyp1 ptyp2 -> failure x
  AbsLang.PTDist ptyp -> failure x
  AbsLang.PTProd tmembers -> failure x
  AbsLang.PTSum tmembers -> failure x
  AbsLang.PTAll ident ptyp -> failure x
  AbsLang.PTInd ident ptyp -> failure x

transTMember :: AbsLang.TMember -> Result
transTMember x = case x of
  AbsLang.TMember ident ptyp -> failure x
  AbsLang.TMember1 ident ptyp -> failure x
